Traceback (most recent call last):
  File "/home/yxz230014/Defeasible_Visual_Entailment_agent_test/Evaluator/visual_text_training_golden.py", line 489, in <module>
    main()
  File "/home/yxz230014/Defeasible_Visual_Entailment_agent_test/Evaluator/visual_text_training_golden.py", line 464, in main
    model = BERTModelModule(model_name=model_name, use_classification_head=args.use_classification_head, classification_weight=args.classification_weight).to(device)
  File "/home/yxz230014/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/home/yxz230014/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/yxz230014/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/yxz230014/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/yxz230014/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/home/yxz230014/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.